### ISSUE TITLE
Generated C file conflicts with Haskell file in build

### ISSUE THREAD

**Issue by chpatrick** [fpco/inline-c#21]
> (00:56:32) rwbarton: oh you have a C file named Clang/FFI.c, and also a Haskell file named Clang/FFI.hs!
> (00:56:34) rwbarton: that won't end well
> (00:56:58) rwbarton: since they both compile to dist/build/Clang/FFI.o

This kills the build.

**Comment by bitonic** [comment]
If you're using cabal (at least the versions I've tested) the compiled object files for che C files are put in different paths -- `dist/build/src` and `dist/build` directly.  Could you upload a cabal project that triggers that behaviour?

**Comment by bitonic** [comment]
Oh, I see when this might happen -- if you don't have a separate `src` directory.  The quick solution is to put your Haskell code in a separate src directory.

Apart from that, we should probably solve this by putting all the C files in a separate directory.  `cabal` itself could (should?) work around this, and put the objects resulting from C files in a separate directory.

**Comment by mitchellwrosen** [comment]
I just got bit by this as well, trying to play with a simple `main-is: Main.hs` with `hs-source-dirs: .`.

**Comment by bitonic** [comment]
Right.  I've been thinking about this, and the proper solution is to put the C files in some separate directory.  However, I'm stuck on deciding on what this directory should be, since configuring TH behaviour is... tricky.

In any case, I'll definitely fix this in the next week.  Any input welcome!

**Comment by bitonic** [comment]
The plan for this is:

* Allow setting the variable location where the files is set by an env variable.
* If said env variable is not present, see if GHC was invoked by cabal.  If it is, find the .cabal file by traversing the directory structure upwards, and place the file in a predefined directory (e.g. `inline-c`).
* Otherwise, fall back to the method we're using now.

I'm aiming to get this done by Wed :)

**Comment by bitonic** [comment]
@mboes is the above what you were thinking last time we talked about this?

**Comment by mboes** [comment]
Yes. Except I believe all build artifacts should go in Cabal's dist folder, wherever it is, rather than us putting things in new folders that `cabal clean` can't easily get rid of.

**Comment by bitonic** [comment]
@mboes , I don't think that works well, since the C files are tarred up along with the Haskell sources when `cabal sdist`ing.

**Comment by bitonic** [comment]
OK, there is a problem with the plan: if a `.cabal` file has multiple targets, all the C files will be put in the same directory.  This means that to build any of the targets we'd be pulling in all of the C files.  The best way would be to have a separate directory for each target, but I see no easy way to do that without annoying the user (e.g. having to set an env variable or having to install some `Setup.hs` file).

**Comment by jyp** [comment]
What about adding a suffix to the source file, like so:

```
@@ -188,7 +188,7 @@ cSourceLoc ctx = do
       else do
         thisFile <- TH.loc_filename <$> TH.location
         let ext = fromMaybe "c" $ ctxFileExtension ctx
-        return $ Just $ dropExtension thisFile `addExtension` ext
+        return $ Just $ (dropExtension thisFile ++ "_inline_c") `addExtension` ext
 
 removeIfExists :: FilePath -> IO ()
 removeIfExists fileName = removeFile fileName `catch` handleExists
```

**Comment by bitonic** [comment]
The reason why I don't like that so much is that it makes specifying the source files in the `.cabal` less simple. I don't have a very strong opinion about this though.

Arguably the "right" solution here is to fix `.cabal` to place object files from C in a different place, that should not be too hard...

**Comment by bitonic** [comment]
Your solution also breaks all previous `.cabal` files using `inline-c`. I'd be much happier if we just fixed cabal, but I don't predict I'll have time to look into it super soon.

**Comment by YPares** [comment]
Got bit by it too. @bitonic As you suggested earlier in the discussion, the cleanest solution is to put the generated C files in another directory. But that also breaks existing cabal configs.
In both cases that's a pretty quick fix for users: when bumping `inline-c` version, just change the paths of your `c-sources` along with it.

**Comment by bitonic** [comment]
@YPares regarding "putting files in another directory", I couldn't come up with a simple scheme that would work in every case.

I think the best option for now might just be to somehow catch this error and tell the user to change the `hs-source-dir`. Maybe it's possible to check its value in `Setup.hs`.

**Comment by bitonic** [comment]
So, it is possible to check this using `Setup.hs` (see the various `hsSourceDirs` fields in http://haddock.stackage.org/lts-5.11/Cabal-1.22.8.0/Distribution-PackageDescription.html#t:PackageDescription ), but that would require the user to use a custom `Setup.hs`.

I don't think it's possible to detect the build directories from within `inline-c`.

**Comment by dcoutts** [comment]
Right, the "right thing"tm is for inline-c to put the generated .c file in the appropriate place within the dist dir, much like Cabal does this for .hsc files and the corresponding generated .hs (or similarly with .chs and generated .c files).

Then the question becomes, how does inline-c know what the right place ought to be? With the .c files ghc itself generates for FFI-exports it gets told via various command line params. For pre-processors, then Cabal tells them via -o flags etc. So what about "pre-processors as libs" like inline-c? Good question. But probably it requires some sensible new standard/convention to be implemented within GHC or Cabal and then inline-c to use that (when available). Suggestions? Env vars, some TH extension that picks up and provides info provided to ghc (e.g. -stubdir)?

If I recall correctly it is the ghc -stubdir flag that tells ghc itself where to place generated .c files arising from FFI exports. Perhaps a TH extension that simply provides this value would work. That has the advantage of consistency between what ghc itself does, and uses the same mechanism that build tools already know about.

Does anyone see a problem with this?

**Comment by dcoutts** [comment]
Or more radical: extend TH to support injecting C code into the *same* output file as GHC generates for FFI exports. This would mean you could mix inline-c and FFI exports in the same .hs file, without the two clobbering each other. It would also mean that users would not have to list the generated .c file in the .cabal file at all, and it would be automatically picked up by the Cabal build system (and any other build system that supports GHC's FFI export mechanism).

**Comment by mboes** [comment]
> Or more radical: extend TH to support injecting C code into the same output file as GHC generates for FFI exports.

I like this idea a lot, not least because I suspect it's doable without any extension at all.

inline-java does pretty much that: get the foreign compiler to spit out some "object code" (bytecode in the java case), then grab that code and inject it in the binary. Add a static pointer to the embedded code. That way `main` can list all static pointers of some magic type, then load all object code it finds.

Because this is C, it should be possible to do something simpler. We should be able to link the object code statically somehow, rather than embed it and then load it dynamically.

**Comment by mboes** [comment]
> So what about "pre-processors as libs" like inline-c? Good question. But probably it requires some sensible new standard/convention to be implemented within GHC or Cabal and then inline-c to use that (when available). Suggestions? Env vars, some TH extension that picks up and provides info provided to ghc (e.g. -stubdir)?

An env var is implementable now, without any extension - just need users to add a custom hook in Setup.hs, provided by inline-c. It can also be opt-in, so that those users that haven't yet added the custom hook will still have their C file generated at the usual place, so the .cabal file doesn't need to change. Backwards compatible.

Further, because the env var can be inline-c specific and inline-c private, it doesn't matter much that env vars are typo prone. We just need to trust the Setup.hs hook implemented once in the inline-c library.

The advantage of making `-stubdir` available via TH though is that it would make code using inline-c buildable without Cabal. plain `ghc --make` would work. Though we'd need to additionally have `addModStub`, similar to the existing `addModDecl`, to let GHC know that there's some extra object code it ought to generate and link in.

**Comment by bitonic** [comment]
I don't have the required context to fully understand these plans, but if anybody comes with a implementation plan that results in simpler usage and more robust build system I'll implement it. Or even better, if anybody wants to implement it, I'll accept the patches!

**Comment by nh2** [comment]
A fix for this is on the way: https://ghc.haskell.org/trac/ghc/ticket/13237

**Comment by bitonic** [comment]
@nh2 @mboes https://phabricator.haskell.org/D3106 is now merged. Do I understand correctly that this will mean that with GHC 8.2 we will be able to just use `addCStub` and be done with the annoying extra files?

**Comment by mboes** [comment]
@bitonic if that patch does its job properly, then yes. :)

Since GHC releases are few and far between, might be good to add the support for this in inline-c from now to see if there are any changes to that patch that need to be made prior to 8.2.

**Comment by bitonic** [comment]
That's fantastic, thanks @facundominguez for this work!

@mboes I'll try to add support for this this week.

**Comment by bitonic** [comment]
Finally, when this lands https://phabricator.haskell.org/D3280 , we'll be able to get rid of the .c files, and thus this issue will be fixed, together with #50 and #52 and #29 .

**Comment by nh2** [comment]
> Finally, when this lands https://phabricator.haskell.org/D3280

That has landed now.

I have also ported that back to GHC 8.0.2 so that inline-c can adapt to it without efforts, see the source and bindist here: [ghc-8.0.2-foreignfiles-backport-release](https://github.com/nh2/ghc/releases/tag/ghc-8.0.2-foreignfiles-backport-release)

**Comment by bitonic** [comment]
OK, I have now produced a branch taht uses `addForeignFile` using @nh2 bindist, see addForeignFile-niklas-bindist .

**Comment by mboes** [comment]
@bitonic any plans to merge that branch? Or can this issue be closed now?

**Comment by bitonic** [comment]
I'll close this when 8.2 is released and we can release the new version in
hackage.
