### ISSUE TITLE
C files regenerated too often

### ISSUE THREAD

**Issue by snoyberg** [fpco/inline-c#24]
Any time the file is type checked- which includes generating haddocks- .c files are regenerated, which forces build systems to recompile the entire project, even if no changes have occurred. Instead: inline-c should check if there is any difference between the old and new content before writing out to the .c file to avoid unnecessary recompiles.

**Comment by bitonic** [comment]
I'm thinking on how to solve this.

Initially I planned to compare the timestamp of the Haskell file with the timestamp of the C file, but that is not robust to changes to the `inline-c`: so for example it might be that the C file is up to date (i.e. it's newer than the Haskell file), but that the `inline-c` library version has changed in the meanwhile.

What we'd really like to know is why the current file is getting type-checked, since GHC already knows if it's re-type-checking because the file has changed or because of some ancillary task (e.g. haddock).  In the case of a "proper" change, we'd write to the C file too, while in the case of haddock or similar tasks we'd leave the file alone.  I'll investigate.

**Comment by mboes** [comment]
As a workaround, we can detect whether the current executable name is
`haddock`, or whether it's `ghc`. In the former case we know that no code
will be generated, and therefore we don't need to generate C code either.
Alternatively, detect whether the config option corresponding to
`-fno-code` has been set, but I doubt that's possible from within TH.

**Comment by bitonic** [comment]
Yeah, for haddock only that would work -- assuming that haddock actually type-checks the file itself, and doesn't fork out to GHC to do that.

@snoyberg , was your quick workaround involving header files working in the end?

**Comment by mboes** [comment]
Haddock uses the GHC API, which is why I suggest that workaround. "Should be" (tm) a simple case of checking the value of argv0.

**Comment by mboes** [comment]
Just tested this special casing "haddock" by calling `getProgName` inside the splice. Works fine.

**Comment by bitonic** [comment]
Reopening this since #26 only addresses a specific case.

**Comment by mboes** [comment]
We should close this unless there are concrete uses case for which solving this in general would be useful. Otherwise this ticket may well linger open forever. We should document in the code/haddock that regenerating the C files even when GHC or some GHC API client app isn't generating any code is a known limitation. If this is a problem for someone they can reopen the ticket.

**Comment by snoyberg** [comment]
I agree with Mathieu.

**Comment by bitonic** [comment]
Fair enough, closing.
