### ISSUE TITLE
Pure blocks?

### ISSUE THREAD

**Issue by mitchellwrosen** [fpco/inline-c#38]
Is there any way to write "pure" blocks? For example,

```haskell
foo :: CInt
foo = [C.pureBlock| int {
    int out;
    some_func(&out);
    return out;
} |]
```

Or, as a workaround, I wonder if this is equivalent?

```haskell
foo :: CInt
foo = unsafePerformIO [C.block| int {
    int out;
    some_func(&out);
    return out;
} |]
```

EDIT: Ah, I see you expose the internal module. I think I can just define it myself:

```haskell
pureBlock :: QuasiQuoter
pureBlock = genericQuote Pure (inlineItems Safe)
```

**Comment by bitonic** [comment]
Glad you found that yourself, sorry about the delay.

It's a feature that we're currently not leveraging, but I did not kill the code.  Note that using `genericQuote Pure` has some consequences regarding the type which is derived by `inline-c`.  Specifically, for function pointers, if you pass `Pure` it's going to expect pure Haskell functions.

My position is that using `unsafePerformIO` explicitly is better because it emphasizes the risks of running C code in a pure fashion, but maybe a module that does that is convenient anyhow...
